<?php

/**
 * This file was auto-generated by `php bin/console make:test`.
 * The actual unit tests have been moved to tests/Service/ForumPostManagerTest.php
 * following the project's folder organisation convention.
 *
 * Run all tests with: php bin/phpunit
 */

namespace App\Tests;

use PHPUnit\Framework\TestCase;

class ForumTest extends TestCase
{
    /**
     * Placeholder: see tests/Service/ForumPostManagerTest.php for full tests.
     */
    public function testForumPostManagerTestsExist(): void
    {
        $this->assertFileExists(
            __DIR__ . '/Service/ForumPostManagerTest.php',
            'ForumPostManagerTest.php should exist in tests/Service/'
        );
    }
}
